### ISSUE TITLE
Rentals Transactional Methods and Queries

### ISSUE THREAD

**Issue by jthompsonnait** [DMIT-2018/dmit-2018-2024-a01-workbook-jthompsonnait#4]
# Task List

This task list area will be completed after the outlined implementation plan.
This area is where one creates the task list associated with the milestone.
The tasks that are outlined below in this area are the tasks that are counted for the milestone.
- [ ] Create Data Models
  - Create Query Models 
    - Fetch RentalService _FetchByPhone
    - Fetch AvailableEquipment_FetchEquipments
    - Fetch RentalService _FetchByRentalNum
    - Fetch CustomerRecord_Pick
    - Fetch CustomerTransaction_Pay
    - Fetch Customer_Return
         
  - Create Command Models For Renting
    - [ ] Search Button
        - The search loop button will search for the customer and display the customer information.t will also display a list of rentals that the selected customer did previously.        
    - [ ] Coupon Search Button - Search_FetchCoupon
        - The search Coupon will validate if the coupon exists and apply it to the customer transaction.
    - [ ] Add Button - AvailableTools_Add_Delete_Equipment
       - The Add button will select a tool and add it to the customer rental list he wants to check out. Also, 
                                          removes the rental equipment from the available list.
    - [ ] Delete Button - AvailableTools_Add_Delete_Equipment
       - The delete button removes rental equipment from the list and returns it to the available list.
    - [ ] Cancel Button
       - The Cancel button terminates the current rental and clears the form.
    - [ ] Rent Button - ToolEquipment_Rent
       - This button will create a rental record and flag the rented equipment as unavailable.
                                       

     - Create Command Models For Returning
    - [ ] Rental Button
       - This button will search for the customer and display his rental record list based on the rental number.                  
    - [ ] Phone Button
       - This button will search for the customer and display his rental record list based on his phone number. 
    - [ ] Pick Button
       - This button will select the rental transaction the customer wants to return.
    - [ ] Pay Button - CustomerTransaction_Pay
       - This button will calculate costs based on the required rental length (Days) presented. 
       - Update Rentals record: subtotal, taxes, rental date in, payment type.
    - [ ] Return Button - Customer_Return
        - Will create a rental record and flag the rented equipment as unavailable.
        - Update RentalDetail records: rental days, In condition, Comments.

    
- [ ] Create Transactional Services  for Renting (methods)
   - [ ] Add a Tool rental.
   - [ ] Remove a Tool rental.
   - [ ] Create a rental record.
   - [ ] Create rental details

 - [ ] Create Transactional Services  for Returning (methods)
   - [ ] Pick a Rental transaction.
   - [ ] Pay the transaction.
   - [ ] Return the Equipment.

**Comment by jthompsonnait** [comment]
# UI Experience


This comment outlines the actions that can be taken on the forms.  Action is responding to the user interacting with the form, pressing the buttons or controls.

## Expected Renting Screen.

![image](https://user-images.githubusercontent.com/90473402/202055548-e7015712-c255-4b41-a831-c24130d4a174.png)

> **PRG** *Post Redirect Get*
> Using routing parameters {searchPhone}
- GET on page load, AvailableEquipment_FetchEquipments(...) will populate the available equipment table.
> - Rule: Equipment must be returned and displayed in clean working order in the available equipment table.
- PRG clicking on the phone search button will retrieve existing records of the customer RentalService _FetchByPhone(int PhoneNum).
> - Rule: In the rental screen, the user cannot select previous rental records or modify any existing ones.
- PRG clicking on the search coupon will validate that the coupon is valid Search_FetchCoupon(string coupon).
- PRG clicking the Cancel empties bound properties and routing parameters (page only).
- Post/PRG clicking the ADD on available equipment will attempt to add the equipment to the customer rental cart void AvailableTools_Add_Delete_Equipment(int Equipmentid).
- Post/PRG  clicking the delete(X) will remove the selected equipment from the rental cart  void AvailableTools_Add_Delete_Equipment(int Equipmentid).
- Post/PRG clicking Rent will create a new rental record for the customer ToolEquipment_Rent.
> - Rule 1: The default renting date is tomorrow's date.
> - Rule 2: The default rental length is 1.
> - Rule 3: The rental record will be created for each piece of equipment then, they will be flagged as unavailable and will no longer be displayed in the available equipment. The rental customer record will be saved to his profile.


## Expected Renting Screen.

![image](https://user-images.githubusercontent.com/90473402/204896744-f30e29ba-5cb6-4f10-b113-7c8508c38ec4.png)


> Using routing parameters {searchPhone}/{Rentals}
- PRG clicking on the Rental button will display the table of rented equipment associated with this number RentalService _FetchByRentalNum (...).
- PRG clicking on the Phone button will display the customer rental records RentalService _FetchByPhone(...).
- PRG clicking on the Pick button will display the customer rental records CustomerRecord_Pick(...).
> - Rule: The Search will be done using the rental or phone numbers.
- POST/PRG clicking on Pay will display the bill to be paid for equipment that is already returned. It will calculate the subtotal, add GST, apply the coupon discount and calculate the rental total. Also, it will save the date of return, subtotal, and tax amount to the database.
> - Rule: The pay calculation requires rental length days to be present and requires a method of payment to be selected. 
> - Rule: The payment will be applied only on returned items and not paid for yet.

               
- POST/PRG clicking Return will :
    1. Update the rental days, In conditions, and Comments.
    2. Update RentalEquipment records: Condition, Available
> - Rule: The return button will require In condition to be selected. Comments are optional.
